name: release-ubuntu-22.04

on:
  push:
    paths:
      - '.github/workflows/ubuntu-22.04.yml'
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Check Server Performance
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号（降序）：7763，8370C，8272CL，8171M，E5-2673 \n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息："
        echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT
        lsb_release -a && which cmake && cmake --version
        pwd

    - name: Prerequisites
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt update
        sudo apt install -y -qq python3 python3-dev python3-setuptools gcc libtinfo-dev zlib1g-dev libzstd-dev libxml2-dev build-essential cmake libedit-dev

    - name: Clone
      run: |
        git clone --recursive https://github.com/microsoft/T-MAC.git
        du -sh *

    - name: Build
      run: |
        pip install virtualenv
        pip list | grep virtualenv
        virtualenv venv && source venv/bin/activate && cd T-MAC && pip install -e . -v && source build/t-mac-envs.sh

    - name: Summary
      run: |
        du -sh *
        du -sh ../*
